const products = [
  {
    _id: '1',
    name: 'BadaBeanBadaBoom',
    image: '/images/BadaBean.png',
    description: 'Vegan snack',
    price: 8.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Beyondchipz',
    image: '/images/BeyondChips.png',
    description: 'Vegan snack',
    price: 7.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Daily Crunch',
    image: '/images/dailyCrunch.png',
    description: 'Vegan snack',
    price: 12.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Earth Balance Vegan Cheddar Squares',
    image: '/images/earthBalance.png',
    description: 'Vegan snack',
    price: 6.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: "Emmy's Coconut Cookies",
    image: '/images/emmys.png',
    description: 'Vegan snack',
    price: 4.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Gorager Project Cheezy Greens',
    image: '/images/Forager.png',
    description: 'Vegan snack',
    price: 4.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
